### ISSUE TITLE
Warning in SPRITE.C

### ISSUE THREAD

**Issue by sandord** [ReservoirGods/GODLIB#1]
I just got this little warning. I know its harmless but still...

    Warning: C:\...\PUREC\INCLUDE\GODLIB\SPRITE\SPRITE.C 391: 'lWith' is assigned a value which is
        never used in function Sprite_CreatePreShifted

**Comment by pink-rg** [comment]
Good point. I have cleaned this up.
Going to run static analysis on the codebase, there are a few issues like this that aren't surfaced by MSVC even at warning level 4.
