### ISSUE TITLE
Can't compile MEMORY

### ISSUE THREAD

**Issue by sandord** [ReservoirGods/GODLIB#2]
C:\...\PURE_C\INCLUDE\GODLIB\MEMORY\MEMORY:
        Undefined symbol: 'Memory_Clear'

This happens as well when building the Sprite sample.

So I'm using Pure C in Steem on TOS 2.06 and 4 megs of ram.

I know that there was a recent commit that optimizes memory clearing using assembly code but somehow the C/assembly switching mechanism doesn't work.

**Comment by pink-rg** [comment]
Missing link to the new assembly language version of the memory routines in this sample. It would be nice if PRJs were more modular, and I could include a base GODLIB.PRJ in all the samples, instead of having to manually update each one. This is fixed now.

**Comment by sandord** [comment]
Great! Thanks a lot.

Perhaps you could mention such changes in a version history file or Wiki page or something. That would save us from painstakingly discovering such solutions or alternatively bothering you everytime this happens ;-)
