### ISSUE TITLE
Sprite_MaskCreate doesn't work for sprites wider than 16 pixels

### ISSUE THREAD

**Issue by sandord** [ReservoirGods/GODLIB#5]
The `lpSrc = apGfx;` statement here, should sit outside of the while loop as it currently re-reads the same first 16 pixels.

https://github.com/ReservoirGods/GODLIB/blob/224cd0f8933f304557184fd2657939987f9abe1c/SPRITE/SPRITE.C#L129

**Comment by pink-rg** [comment]
Good spot. Fix should be as described.

**Comment by pink-rg** [comment]
Fixed now.
