### ISSUE TITLE
Is this something we need to worry about? ;-)

### ISSUE THREAD

**Issue by sandord** [ReservoirGods/GODLIB#6]
https://github.com/ReservoirGods/GODLIB/blob/6226582bd20abceca688b4a8dbd2031c66ac3f1f/GRAPHIC/GRF_4_S.S#L2796

Seriously though, does this indicate there might be a problem with the code there?

**Comment by pink-rg** [comment]
Lol no. I should delete this. Was just an easy label to find in MonST for debugging.

**Comment by pink-rg** [comment]
Removed this label now.

**Comment by sandord** [comment]
I just found another one :-)

https://github.com/ReservoirGods/GODLIB/blob/2debb30e55e94cc665e23ffb3956e0d1b7d0593f/GRAPHIC/GRF_B4_S.S#L661

**Comment by pink-rg** [comment]
nuked.
